/// Represents a structured RFQ (Request for Quotation) generated by Gemini AI
/// and stored in the Firestore "rfqs" collection.
class RfqModel {
  final String id;
  final String buyerId;
  final String requirementText;
  final String status; // open | sent | closed
  final String category;
  final int quantity;
  final double targetPrice;
  final String deadline;
  final String specifications;
  final String description;
  final bool aiParsed;
  final String createdAt;

  const RfqModel({
    required this.id,
    required this.buyerId,
    required this.requirementText,
    this.status = 'open',
    this.category = '',
    this.quantity = 1,
    this.targetPrice = 0.0,
    this.deadline = '',
    this.specifications = '',
    this.description = '',
    this.aiParsed = false,
    this.createdAt = '',
  });

  factory RfqModel.fromJson(Map<String, dynamic> json) {
    return RfqModel(
      id:               json['id']?.toString() ?? '',
      buyerId:          json['buyer_id']?.toString() ?? '',
      requirementText:  json['requirement_text']?.toString() ?? '',
      status:           json['status']?.toString() ?? 'open',
      category:         json['category']?.toString() ?? '',
      quantity:         (json['quantity'] as num?)?.toInt() ?? 1,
      targetPrice:      (json['target_price'] as num?)?.toDouble() ?? 0.0,
      deadline:         json['deadline']?.toString() ?? '',
      specifications:   json['specifications']?.toString() ?? '',
      description:      json['description']?.toString() ?? '',
      aiParsed:         json['ai_parsed'] == true,
      createdAt:        json['created_at']?.toString() ?? '',
    );
  }

  Map<String, dynamic> toJson() => {
    'id':               id,
    'buyer_id':         buyerId,
    'requirement_text': requirementText,
    'status':           status,
    'category':         category,
    'quantity':         quantity,
    'target_price':     targetPrice,
    'deadline':         deadline,
    'specifications':   specifications,
    'description':      description,
    'ai_parsed':        aiParsed,
    'created_at':       createdAt,
  };

  /// Total estimated budget
  double get estimatedBudget => targetPrice * quantity;
}
