# -*- coding: utf-8 -*-
"""
Diagnostic script - Part 2: Deep dive into why Google STT fails
even for WAV files.
"""
import os
import sys
import io
import wave
import json
import logging
import traceback
import struct

# Force UTF-8 output on Windows
sys.stdout.reconfigure(encoding='utf-8')

import speech_recognition as sr

logging.basicConfig(level=logging.DEBUG, format="%(levelname)s | %(name)s | %(message)s")
logger = logging.getLogger("debug_speech2")

WAV_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "sample_audio.wav")

# ---------------------------------------------------------------------------
# 1. Analyze sample_audio.wav content — is it silence or real speech?
# ---------------------------------------------------------------------------
print("=" * 60)
print("STEP 1: Analyzing sample_audio.wav content")
print("=" * 60)

with wave.open(WAV_PATH, "rb") as wf:
    nchannels = wf.getnchannels()
    sampwidth = wf.getsampwidth()
    framerate = wf.getframerate()
    nframes = wf.getnframes()
    frames = wf.readframes(nframes)

duration = nframes / framerate
print(f"Duration     : {duration:.2f}s")
print(f"Channels     : {nchannels}")
print(f"Sample width : {sampwidth} bytes")
print(f"Frame rate   : {framerate} Hz")
print(f"Total frames : {nframes}")
print(f"Raw data len : {len(frames)} bytes")

# Check if the audio is all silence/zeros
samples = struct.unpack(f"<{nframes}h", frames)
max_val = max(abs(s) for s in samples)
avg_val = sum(abs(s) for s in samples) / len(samples)
nonzero = sum(1 for s in samples if s != 0)

print(f"\nMax amplitude   : {max_val} (out of 32767)")
print(f"Avg amplitude   : {avg_val:.1f}")
print(f"Non-zero samples: {nonzero} / {len(samples)} ({100*nonzero/len(samples):.1f}%)")

if max_val < 100:
    print("\n>>> PROBLEM FOUND: Audio is essentially SILENCE!")
    print("    The WAV file contains near-zero samples (no real speech).")
    print("    This was likely generated by create_test_assets.py as a synthetic placeholder.")
elif max_val < 500:
    print("\n>>> WARNING: Audio volume is extremely low — may be unintelligible.")
else:
    print(f"\n>>> Audio appears to have real content (max={max_val}).")

# ---------------------------------------------------------------------------
# 2. Try Google Web Speech API with the sample WAV — capture the raw response
# ---------------------------------------------------------------------------
print("\n" + "=" * 60)
print("STEP 2: Testing Google Web Speech API with detailed error capture")
print("=" * 60)

recognizer = sr.Recognizer()
recognizer.energy_threshold = 300

try:
    with sr.AudioFile(WAV_PATH) as source:
        audio_data = recognizer.record(source)

    # Manually call recognize_google and intercept the raw response
    try:
        result = recognizer.recognize_google(audio_data, language="hi-IN", show_all=True)
        print(f"\nGoogle API raw response (show_all=True):")
        print(json.dumps(result, indent=2, ensure_ascii=False) if isinstance(result, dict) else repr(result))

        if not result:
            print("\n>>> Google returned EMPTY result — audio was not recognized.")
            print("    This confirms: the WAV is silence/garbage, or no speech was detected.")
        else:
            print("\n>>> Google DID return results!")
    except sr.UnknownValueError:
        print("\n>>> UnknownValueError from Google — audio not recognized at all.")
    except sr.RequestError as e:
        print(f"\n>>> RequestError: {e}")
        print("    This could mean the free API rate limit was hit, or network issue.")
except Exception as e:
    print(f"\nFailed to load audio: {e}")
    traceback.print_exc()

# ---------------------------------------------------------------------------
# 3. Check what create_test_assets.py generates
# ---------------------------------------------------------------------------
print("\n" + "=" * 60)
print("STEP 3: Checking create_test_assets.py to understand WAV origin")
print("=" * 60)

test_assets_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "create_test_assets.py")
if os.path.exists(test_assets_path):
    with open(test_assets_path, "r", encoding="utf-8") as f:
        content = f.read()
    # Find any WAV generation code
    for i, line in enumerate(content.split("\n"), 1):
        line_lower = line.lower()
        if any(kw in line_lower for kw in ["wav", "audio", "sample", "sine", "tone", "frequency", "numpy"]):
            print(f"  L{i}: {line.rstrip()}")
else:
    print("  create_test_assets.py not found")

# ---------------------------------------------------------------------------
# 4. Check pydub and ffmpeg status
# ---------------------------------------------------------------------------
print("\n" + "=" * 60)
print("STEP 4: MP3 handling capabilities")
print("=" * 60)

try:
    import pydub
    print(f"  pydub: INSTALLED (v{pydub.__version__})")
except ImportError:
    print("  pydub: NOT INSTALLED")

import shutil
ffmpeg = shutil.which("ffmpeg")
print(f"  ffmpeg: {ffmpeg or 'NOT FOUND'}")

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
print("\n" + "=" * 60)
print("DIAGNOSIS SUMMARY")
print("=" * 60)
print("""
ROOT CAUSE ANALYSIS:
===================
1. The sample_audio.wav is a SYNTHETIC placeholder (generated by
   create_test_assets.py) — it contains either silence or a sine wave,
   NOT real speech. Google STT correctly reports it as unintelligible.

2. For real MP3 files (user's case): the code at speech_service.py L74
   checks if bytes start with 'RIFF'. MP3 files start with 'ID3' or
   0xFF sync bytes. The code then WRAPS compressed MP3 data as raw PCM
   in a WAV container — creating corrupt garbage audio.

3. Neither pydub nor ffmpeg is available for proper MP3-to-WAV conversion.

4. The SpeechRecognition library's sr.AudioFile ONLY supports WAV, AIFF,
   and FLAC natively. MP3 requires pydub + ffmpeg.

RECOMMENDED FIX:
================
Install pydub + ffmpeg, OR (better for this project):
Use the google-genai SDK (already installed!) which can transcribe
audio natively from MP3/WAV without any conversion needed.
""")
